import { Game, GameStatus, Genre, Platform } from '@/types';

export const sampleGames: Game[] = [
  {
    id: '1',
    title: 'The Legend of Zelda: Breath of the Wild',
    genres: [Genre.ACTION, Genre.ADVENTURE],
    platforms: [Platform.NINTENDO_SWITCH],
    status: GameStatus.COMPLETED,
    rating: 9,
    hoursPlayed: 120,
    completionDate: new Date('2024-01-15'),
    startDate: new Date('2023-12-01'),
    notes: 'Amazing open world experience',
    coverImageUrl: '',
    releaseDate: new Date('2017-03-03'),
    developer: 'Nintendo',
    publisher: 'Nintendo',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Cyberpunk 2077',
    genres: [Genre.RPG, Genre.ACTION],
    platforms: [Platform.PC, Platform.PLAYSTATION_5],
    status: GameStatus.CURRENTLY_PLAYING,
    rating: 7,
    hoursPlayed: 45,
    startDate: new Date('2024-01-01'),
    notes: 'Great story, some bugs',
    coverImageUrl: '',
    releaseDate: new Date('2020-12-10'),
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    title: 'Hades',
    genres: [Genre.ACTION, Genre.INDIE],
    platforms: [Platform.PC, Platform.NINTENDO_SWITCH],
    status: GameStatus.WANT_TO_PLAY,
    coverImageUrl: '',
    releaseDate: new Date('2020-09-17'),
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '4',
    title: 'Red Dead Redemption 2',
    genres: [Genre.ACTION, Genre.ADVENTURE],
    platforms: [Platform.PC, Platform.PLAYSTATION_4, Platform.XBOX_ONE],
    status: GameStatus.ON_HOLD,
    rating: 8,
    hoursPlayed: 25,
    startDate: new Date('2023-11-15'),
    notes: 'Beautiful game but very slow paced',
    coverImageUrl: '',
    releaseDate: new Date('2018-10-26'),
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2023-12-01'),
  },
  {
    id: '5',
    title: 'FIFA 24',
    genres: [Genre.SPORTS],
    platforms: [Platform.PLAYSTATION_5, Platform.XBOX_SERIES],
    status: GameStatus.DROPPED,
    rating: 5,
    hoursPlayed: 10,
    startDate: new Date('2023-10-01'),
    notes: 'Same as last year',
    coverImageUrl: '',
    releaseDate: new Date('2023-09-29'),
    developer: 'EA Sports',
    publisher: 'Electronic Arts',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2023-10-15'),
  },
]; 