import { Game, GameStatus, Genre, Platform } from '@/types';

export const sampleGames: Game[] = [
  {
    id: '1',
    title: 'The Legend of Zelda: Breath of the Wild',
    description: 'Step into a world of discovery, exploration, and adventure in The Legend of Zelda: Breath of the Wild. Travel across vast fields, through forests, and to mountain peaks as you discover what has become of the kingdom of Hyrule in this stunning Open-Air Adventure.',
    genres: [Genre.ACTION, Genre.ADVENTURE],
    platforms: [Platform.NINTENDO_SWITCH],
    status: GameStatus.COMPLETED,
    rating: 9,
    hoursPlayed: 120,
    completionDate: new Date('2024-01-15'),
    startDate: new Date('2023-12-01'),
    notes: 'Amazing open world experience. The freedom to explore and approach problems in multiple ways is incredible. The physics engine creates endless possibilities for creative solutions.',
    coverImageUrl: '',
    releaseDate: new Date('2017-03-03'),
    developer: 'Nintendo',
    publisher: 'Nintendo',
    createdAt: new Date('2023-12-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    title: 'Cyberpunk 2077',
    description: 'Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.',
    genres: [Genre.RPG, Genre.ACTION],
    platforms: [Platform.PC, Platform.PLAYSTATION_5],
    status: GameStatus.CURRENTLY_PLAYING,
    rating: 7,
    hoursPlayed: 45,
    startDate: new Date('2024-01-01'),
    notes: 'Great story and characters, especially Keanu Reeves as Johnny Silverhand. The city is beautifully designed but still has some technical issues. Much improved since launch.',
    coverImageUrl: '',
    releaseDate: new Date('2020-12-10'),
    developer: 'CD Projekt Red',
    publisher: 'CD Projekt',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    title: 'Hades',
    description: 'Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant\'s critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre.',
    genres: [Genre.ACTION, Genre.INDIE],
    platforms: [Platform.PC, Platform.NINTENDO_SWITCH],
    status: GameStatus.WANT_TO_PLAY,
    notes: 'Heard amazing things about this game. The art style looks incredible and everyone says the story is fantastic.',
    coverImageUrl: '',
    releaseDate: new Date('2020-09-17'),
    developer: 'Supergiant Games',
    publisher: 'Supergiant Games',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '4',
    title: 'Red Dead Redemption 2',
    description: 'America, 1899. The end of the Wild West era has begun. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive.',
    genres: [Genre.ACTION, Genre.ADVENTURE],
    platforms: [Platform.PC, Platform.PLAYSTATION_4, Platform.XBOX_ONE],
    status: GameStatus.ON_HOLD,
    rating: 8,
    hoursPlayed: 25,
    startDate: new Date('2023-11-15'),
    notes: 'Beautiful game with incredible attention to detail, but the pacing is very slow. The realism sometimes gets in the way of fun gameplay. Will return to it later.',
    coverImageUrl: '',
    releaseDate: new Date('2018-10-26'),
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2023-12-01'),
  },
  {
    id: '5',
    title: 'FIFA 24',
    description: 'EA SPORTS FC 24 welcomes you to The World\'s Game: the most true-to-football experience ever with HyperMotionV, PlayStyles optimised by Opta, and a revolutionized Frostbite Engine.',
    genres: [Genre.SPORTS],
    platforms: [Platform.PLAYSTATION_5, Platform.XBOX_SERIES],
    status: GameStatus.DROPPED,
    rating: 5,
    hoursPlayed: 10,
    startDate: new Date('2023-10-01'),
    notes: 'Feels exactly the same as FIFA 23. The gameplay improvements are minimal and the microtransactions are still aggressive. Not worth the upgrade.',
    coverImageUrl: '',
    releaseDate: new Date('2023-09-29'),
    developer: 'EA Sports',
    publisher: 'Electronic Arts',
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2023-10-15'),
  },
]; 